<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-04-16 07:40:42 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\inventarios\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:41:12 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\inventarios\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:42:52 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\inventarios\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:42:58 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\inventarios\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:44:05 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\inventarios\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:44:56 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\inventarios\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:44:57 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\inventarios\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:49:02 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\lacasita\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 07:51:52 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\lacasita\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 09:21:26 --> Severity: error --> Exception: Call to a member function combo_unidad() on null C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\agregar.php 57
ERROR - 2021-04-16 09:21:51 --> Severity: error --> Exception: Call to a member function combo_unidad() on null C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\agregar.php 57
ERROR - 2021-04-16 09:31:17 --> Severity: error --> Exception: Call to a member function combo_unidad() on null C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\agregar.php 57
ERROR - 2021-04-16 09:31:19 --> Severity: error --> Exception: Call to a member function combo_unidad() on null C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\agregar.php 57
ERROR - 2021-04-16 09:32:24 --> Severity: error --> Exception: Call to a member function combo_unidad() on null C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\agregar.php 57
ERROR - 2021-04-16 09:33:57 --> Severity: error --> Exception: Call to a member function combo_unidad() on null C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\agregar.php 57
ERROR - 2021-04-16 09:37:11 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:37:16 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:37:17 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:39:23 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:39:23 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 16:44:00 --> Severity: 8192 --> Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` C:\xampp\htdocs\varios\qsystem\lacasita\system\helpers\url_helper.php 162
ERROR - 2021-04-16 09:44:00 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:44:00 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:44:59 --> Severity: 8192 --> Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` C:\xampp\htdocs\varios\qsystem\lacasita\system\helpers\url_helper.php 162
ERROR - 2021-04-16 09:44:59 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:44:59 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:45:08 --> Severity: 8192 --> Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` C:\xampp\htdocs\varios\qsystem\lacasita\system\helpers\url_helper.php 162
ERROR - 2021-04-16 09:45:08 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:45:08 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 09:46:27 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:46:30 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:48:08 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:48:44 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:48:45 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:48:45 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:48:46 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:48:46 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:49:15 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:49:36 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:57:51 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:57:51 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 09:59:12 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:59:12 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 09:59:50 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:59:50 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 09:59:53 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 09:59:53 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 10:05:00 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 10:05:00 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 10:06:01 --> Severity: error --> Exception: syntax error, unexpected ';' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 52
ERROR - 2021-04-16 10:06:01 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 10:19:23 --> Severity: error --> Exception: syntax error, unexpected ':' C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 33
ERROR - 2021-04-16 11:10:43 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:10:43 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:10:43 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 68
ERROR - 2021-04-16 11:12:20 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:12:20 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:12:20 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 68
ERROR - 2021-04-16 11:12:23 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:12:23 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:12:23 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 68
ERROR - 2021-04-16 11:17:44 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:17:44 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:17:44 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:18:00 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:18:00 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:18:00 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:20:26 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:20:26 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:20:26 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:20:28 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:20:28 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:20:28 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:20:47 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:20:47 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:20:47 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:20:48 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:20:48 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:20:48 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:20:50 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:20:50 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:20:50 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:21:12 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:21:12 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:21:12 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:21:13 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:21:13 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:21:13 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:28:40 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:28:40 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:28:40 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 65
ERROR - 2021-04-16 11:29:36 --> Severity: Notice --> Undefined variable: csql C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 66
ERROR - 2021-04-16 11:29:36 --> Severity: Warning --> mysqli::query(): Empty query C:\xampp\htdocs\varios\qsystem\lacasita\system\database\drivers\mysqli\mysqli_driver.php 221
ERROR - 2021-04-16 11:29:36 --> Query error:  - Invalid query: 
ERROR - 2021-04-16 11:29:36 --> Severity: error --> Exception: Call to a member function result() on bool C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\models\Producto_model.php 66
ERROR - 2021-04-16 11:29:36 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 14:36:10 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 157
ERROR - 2021-04-16 14:36:11 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 157
ERROR - 2021-04-16 14:37:08 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:37:25 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:37:43 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:38:11 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:48:11 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:48:58 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:48:59 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:52:16 --> Severity: Warning --> Use of undefined constant ALL - assumed 'ALL' (this will throw an Error in a future version of PHP) C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 157
ERROR - 2021-04-16 14:52:16 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:52:45 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:52:52 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:53:14 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:53:24 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:53:39 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:57:06 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 14:57:28 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 15:03:04 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 15:08:04 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 15:08:16 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 15:08:22 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 15:09:33 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 158
ERROR - 2021-04-16 15:10:05 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 159
ERROR - 2021-04-16 15:10:05 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 159
ERROR - 2021-04-16 15:10:06 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 159
ERROR - 2021-04-16 15:10:07 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 159
ERROR - 2021-04-16 15:10:07 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 159
ERROR - 2021-04-16 15:10:08 --> Severity: error --> Exception: Call to undefined function init_set() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 159
ERROR - 2021-04-16 15:12:21 --> Severity: Notice --> Undefined variable: result C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\controllers\Inventario.php 172
ERROR - 2021-04-16 15:13:22 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 7
ERROR - 2021-04-16 15:13:22 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:14:49 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 7
ERROR - 2021-04-16 15:19:49 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\rep_productos.php 7
ERROR - 2021-04-16 15:19:49 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:19:57 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\rep_productos.php 7
ERROR - 2021-04-16 15:19:57 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:21:08 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\rep_productos.php 7
ERROR - 2021-04-16 15:21:08 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:22:17 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\rep_productos.php 7
ERROR - 2021-04-16 15:22:17 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:22:21 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\producto\views\rep_productos.php 7
ERROR - 2021-04-16 15:22:21 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:23:21 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 7
ERROR - 2021-04-16 15:23:21 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:23:50 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 7
ERROR - 2021-04-16 15:23:52 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 7
ERROR - 2021-04-16 15:24:21 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 7
ERROR - 2021-04-16 15:24:21 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:24:22 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 7
ERROR - 2021-04-16 15:24:22 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:25:27 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:25:27 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:25:29 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:25:29 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:26:10 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:26:10 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:26:11 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:26:11 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:26:13 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:26:13 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:26:15 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:26:15 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:26:39 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:26:39 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:26:40 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:26:40 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:26:41 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:26:41 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:29:03 --> Severity: Notice --> Undefined variable: content C:\xampp\htdocs\varios\qsystem\lacasita\application\views\templates\inv-template.php 56
ERROR - 2021-04-16 15:29:03 --> Severity: Notice --> Undefined variable: _ci_file C:\xampp\htdocs\varios\qsystem\lacasita\application\third_party\MX\Loader.php 336
ERROR - 2021-04-16 15:29:23 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:29:23 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:31:12 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:31:12 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:31:12 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:31:12 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 15:36:41 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:38:14 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:38:16 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:38:26 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:38:27 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:47:23 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:47:26 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:49:52 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 15:49:52 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:06:09 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:06:09 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:06:11 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:06:11 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:07:10 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:07:10 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:07:11 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:07:11 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:08:33 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:08:33 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:08:35 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:08:35 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:08:35 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:08:35 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:09:08 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:09:08 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:09:09 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:09:09 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:10:42 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:10:42 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:10:44 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:10:44 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:10:48 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:10:48 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:15:32 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:15:32 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:16:08 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:16:08 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:16:10 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:16:10 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:16:22 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_productos.php 8
ERROR - 2021-04-16 16:16:22 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:17:02 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 8
ERROR - 2021-04-16 16:17:02 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:17:03 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 8
ERROR - 2021-04-16 16:17:03 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:17:05 --> Severity: error --> Exception: syntax error, unexpected ',', expecting end of file C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 8
ERROR - 2021-04-16 16:17:05 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of ParseError given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(ParseError))
#1 [internal function]: _exception_handler(Object(ParseError))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:37:14 --> Severity: Notice --> Undefined variable: titulo C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 1
ERROR - 2021-04-16 16:37:14 --> Severity: error --> Exception: Cannot use object of type stdClass as array C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 17
ERROR - 2021-04-16 16:37:14 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:38:23 --> Severity: error --> Exception: Cannot use object of type stdClass as array C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 17
ERROR - 2021-04-16 16:38:23 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php on line 658 and defined in C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php:190
Stack trace:
#0 C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Common.php(658): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\xampp\htdocs\varios\qsystem\lacasita\system\core\Exceptions.php 190
ERROR - 2021-04-16 16:53:47 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 16:53:48 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 16:53:57 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 16:54:18 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 16:54:56 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 16:54:58 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 16:55:03 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 16:55:05 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\varios\qsystem\lacasita\application\modules\inventario\views\rep_producto1.php 15
ERROR - 2021-04-16 19:40:08 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\lacasita\application\libraries\google-api-php-client\service\Google_Utils.php 58
ERROR - 2021-04-16 19:42:57 --> Severity: 8192 --> Array and string offset access syntax with curly braces is deprecated C:\xampp\htdocs\varios\qsystem\lacasita\application\libraries\google-api-php-client\service\Google_Utils.php 58
